{
 "title": "MSSQL windows_exporter",
 "description": "Performance and health metrics for your SQL Servers using windows Exporter v0.16 and Prometheus",
 "tags": [
  "SQL Server",
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "90s" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(windows_mssql_collector_duration_seconds, instance)"
    }
   },
   {
    "name": "dbinstance",
    "label": "DB Instance",
    "query": {
     "query": "label_values(windows_mssql_genstats_logical_connections, mssql_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SRV | General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "DEADLOCKS",
   "type": "stat",
   "description": "**DEADLOCKS**\n\nNumber of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_mars_deadlocks{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "RUIG",
   "type": "stat",
   "description": "**RUIG**\n\nNumber of duplicate tempdb recovery unit id generated.",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_tempdb_recovery_unit_ids_generated{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "LOGICAL CONNECTIONS",
   "type": "stat",
   "description": "**LOGICAL CONNECTIONS**\n\nNumber of logical connections to the system.\n\nThe main purpose of logical connections is to service multiple active result sets (MARS) requests. For MARS requests, every time that an application makes a connection to SQL Server, there may be more than one logical connection that corresponds to a physical connection.\n\nWhen MARS is not used, the ratio between physical and logical connections is 1:1. Therefore, every time that an application makes a connection to SQL Server, logical connections will increase by 1.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_logical_connections{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "NETWORK UTILIZATION",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(windows_net_bytes_total{instance=\"$server\"}[$interval])) / sum(windows_net_current_bandwidth_bytes{instance=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "STORAGE",
   "type": "gauge",
   "description": "**STORAGE**\n\nShow drive space usage by percentage.",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(({__name__=~\"^windows_logical_disk_size_bytes.*\", instance=\"$server\", volume!~\"Harddisk.+\"} - {__name__=~\"^windows_logical_disk_free_bytes.*\", instance=\"$server\"}) / {__name__=~\"^windows_logical_disk_size_bytes.*\", instance=\"$server\",volume!~\"Harddisk.+\"} * 100, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "LOGINS-LOGOUTS",
   "type": "bargauge",
   "description": "**LOGINS-LOGOUTS**\n\nTotal number of logins started per second. This does not include pooled connections.\n\nTotal number of logout operations started per second.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(windows_mssql_genstats_logins{mssql_instance=\"$dbinstance\"}[1m])",
     "legendFormat": "Logins/m"
    },
    {
     "expr": "rate(windows_mssql_genstats_logouts{instance=\"$server\", mssql_instance=\"$dbinstance\"}[1m])",
     "legendFormat": "Logins/m"
    }
   ]
  },
  {
   "title": "ACTIVE TEMP TABLES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_active_temp_tables{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "LONGEST TRANSACT RUN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_longest_transaction_running_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "tempDB FREE SPACE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_tempdb_free_space_bytes{instance=\"$server\", mssql_instance=~\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "LOCK WAITS I/O",
   "type": "stat",
   "description": "**LOCK WAITS I/O**\n\nSQL Trace IO Provider Lock Waits",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_sql_trace_io_provider_lock_waits{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
    }
   ]
  },
  {
   "title": "CONNECTIONS RESETS",
   "type": "stat",
   "description": "**CONNECTIONS RESETS**\n\nTotal number of logins started from the connection pool.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(windows_mssql_genstats_connection_resets{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])"
    }
   ]
  },
  {
   "title": "KPI | CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "**CPU Usage**\n\nShow cpu usage by mode.",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (irate(windows_cpu_time_total{instance=\"$server\"}[$interval]))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "gauge",
     "description": "**CPU**\n\nShow CPU usage by percentage.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=~\"idle.*\"}[$interval])) * 100)"
      }
     ]
    },
    {
     "title": "CPU load per process",
     "type": "graph",
     "description": "**CPU load per process**\n\nShow cpu usage by process.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "CPU load" }
     ],
     "targets": [
      {
       "expr": "sum by (process) (rate(windows_process_cpu_time_total{instance=\"$server\", process !~\"Idle\"}[$interval]))",
       "legendFormat": "{{ process }}"
      }
     ]
    },
    {
     "title": "USER CONNECTIONS",
     "type": "stat",
     "description": "**USER CONNECTIONS**\n\nCounts the number of users currently connected to SQL Server.",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "windows_mssql_genstats_user_connections{instance=\"$server\", mssql_instance=~\"$dbinstance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "KPI | Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Physical memory",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(windows_cs_physical_memory_bytes{instance=\"$server\"} - windows_os_physical_memory_free_bytes{instance=\"$server\"}) / windows_cs_physical_memory_bytes{instance=\"$server\"} * 100"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(windows_os_virtual_memory_bytes{instance=\"$server\"} - windows_os_virtual_memory_free_bytes{instance=\"$server\"}) / windows_os_virtual_memory_bytes{instance=\"$server\"} * 100"
      }
     ]
    },
    {
     "title": "Buffer Pool Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_bufman_buffer_cache_hits{instance=\"$server\", mssql_instance=~\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "Free List Stalls/sec",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_bufman_free_list_stalls{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "PAGE WRITES",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_bufman_page_writes{instance=\"$server\", mssql_instance=~\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "DATA FILE SIZE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_data_files_size_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"})"
      }
     ]
    },
    {
     "title": "PLE",
     "type": "stat",
     "description": "**PLE**\n\nIndicates the number of seconds a page will stay in the buffer pool without references.",
     "gridPos": { "h": 6, "w": 2, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_bufman_page_life_expectancy_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "BYTES PER CONNECTION",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (mssql_instance) (windows_mssql_memmgr_connection_memory_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"})"
      }
     ]
    },
    {
     "title": "Target Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_memmgr_target_server_memory_bytes{instance=\"$server\", mssql_instance=~\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "Stolen Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_memmgr_stolen_server_memory_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_memmgr_total_server_memory_bytes{instance=\"$server\", mssql_instance=~\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "Memory Grant Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_memmgr_pending_memory_grants{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "PAGE READS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_mssql_bufman_page_reads{instance=\"$server\", mssql_instance=\"$dbinstance\"}"
      }
     ]
    },
    {
     "title": "LOG USED (%)",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (mssql_instance) (windows_mssql_databases_log_used_percent{instance=\"$server\", mssql_instance=\"$dbinstance\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SQL Server Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(windows_mssql_sqlstats_batch_requests{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Batch Requests/sec"
      },
      {
       "expr": "windows_mssql_genstats_user_connections{instance=\"$server\", mssql_instance=\"$dbinstance\"}",
       "legendFormat": "User Connections"
      },
      {
       "expr": "rate(windows_mssql_genstats_logins{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Logins/sec"
      },
      {
       "expr": "rate(windows_mssql_genstats_logouts{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Logouts/sec"
      },
      {
       "expr": "rate(windows_mssql_sqlstats_sql_compilations{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "SQL Compilations/sec"
      },
      {
       "expr": "rate(windows_mssql_sqlstats_sql_recompilations{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "SQL Re-Compilations/sec"
      },
      {
       "expr": "windows_mssql_genstats_blocked_processes{instance=\"$server\", mssql_instance=\"$dbinstance\"}",
       "legendFormat": "Processes blocked"
      }
     ]
    },
    {
     "title": "Databases Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(windows_mssql_databases_transactions{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Transactions/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_write_transactions{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Write Transactions/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_flushes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Flushes/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_flush_wait_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Flush Wait Time"
      },
      {
       "expr": "sum(rate(windows_mssql_locks_lock_timeouts{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Lock Timeouts/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_group_commit_stall_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Group Stall/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_locks_lock_wait_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Lock Waits/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_disk_reads{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Pool Disc/sec"
      }
     ]
    },
    {
     "title": "Buffer Cache - Disk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(windows_mssql_accessmethods_full_scans{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Full Scans/sec"
      },
      {
       "expr": "rate(windows_mssql_accessmethods_index_searches{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Index Searches/sec"
      },
      {
       "expr": "rate(windows_mssql_accessmethods_page_splits{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Page Splits/sec"
      },
      {
       "expr": "rate(windows_mssql_bufman_page_lookups{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Page lookups/sec"
      },
      {
       "expr": "rate(windows_mssql_bufman_page_reads{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Page reads/sec"
      },
      {
       "expr": "rate(windows_mssql_bufman_page_writes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Page writes/sec"
      },
      {
       "expr": "rate(windows_mssql_bufman_read_ahead_pages{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Readahead pages/sec"
      },
      {
       "expr": "rate(windows_mssql_bufman_lazywrites{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Lazy writes/sec"
      },
      {
       "expr": "rate(windows_mssql_bufman_checkpoint_pages{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "Checkpoint pages/sec"
      }
     ]
    },
    {
     "title": "Memory Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "windows_mssql_memmgr_sql_cache_memory_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}",
       "legendFormat": "SQL Cache"
      },
      {
       "expr": "windows_mssql_memmgr_optimizer_memory_bytes{instance=\"$server\", mssql_instance=~\"$dbinstance\"}",
       "legendFormat": "Optimizer"
      },
      {
       "expr": "windows_mssql_memmgr_log_pool_memory_bytes{instance=\"$server\", mssql_instance=~\"$dbinstance\"}",
       "legendFormat": "Log Pool"
      },
      {
       "expr": "windows_mssql_memmgr_lock_memory_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}",
       "legendFormat": "Lock"
      },
      {
       "expr": "windows_mssql_memmgr_database_cache_memory_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}",
       "legendFormat": "Database Cache"
      },
      {
       "expr": "windows_mssql_memmgr_connection_memory_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}",
       "legendFormat": "Connection"
      }
     ]
    },
    {
     "title": "Lock Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(windows_mssql_locks_lock_requests{instance=\"$server\"}[$interval])",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Ratios",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(windows_mssql_accessmethods_page_splits{instance=\"$server\"}[$interval])",
       "legendFormat": "Pages split/batch request"
      },
      {
       "expr": "rate(windows_mssql_sqlstats_sql_compilations{instance=\"$server\"}[$interval])",
       "legendFormat": "SQL Compilation/batch request"
      },
      {
       "expr": "rate(windows_mssql_bufman_page_reads{instance=\"$server\"}[$interval])",
       "legendFormat": "Read-ahead/page read"
      },
      {
       "expr": "rate(windows_mssql_sqlstats_sql_recompilations{instance=\"$server\"}[$interval])",
       "legendFormat": "SQL Recompilation/batch request"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Size Trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Database | Rows Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(windows_mssql_databases_bulk_copy_rows{instance=\"$server\"}[$interval])",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Database | Log Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_files_size_bytes.*\", instance=\"$server\", mssql_instance=\"$dbinstance\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Latency | FETCH/PEAK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Fetch | DLC Latency (ms)",
     "type": "graph",
     "description": "**Fetch | DLC Latency (ms)**\n\nAverage latency in microseconds between log blocks entering the Direct Log Consumer and being retrieved by the XTP controller, per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_fetch_latency_seconds.*\", instance=\"$server\", mssql_instance=\"$dbinstance\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Peak | DLC Latency (ms)",
     "type": "graph",
     "description": "**Peak | DLC Latency (ms)**\n\nThe largest recorded latency, in microseconds, of a fetch from the Direct Log Consumer by the XTP controller.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_peak_latency_seconds.*\", instance=\"$server\", mssql_instance=\"$dbinstance\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log | Pool Activities",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_cache_misses{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Cache Misses/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_disk_reads{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Disk Reads/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_empty_free_pool_pushes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Empty Free Pool Pushes/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_hash_deletes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Hash Deletes/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_hash_inserts{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Hash Inserts/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_log_scan_pushes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Log Scan Pushes/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_requests{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Requests/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_pool_requests_old_vlf{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Pool Requests Old VLF/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_active_log_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"})",
       "legendFormat": "Log Pool Total Active Log"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_shared_pool_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"})",
       "legendFormat": "Log Pool Total Shared Pool Bytes/sec"
      }
     ]
    },
    {
     "title": "Log | Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(windows_mssql_databases_log_files_size_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Files Size Bytes/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_files_used_size_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Files Used Size Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_wait_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"})",
       "legendFormat": "Log Flush Wait Seconds/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_flush_waits{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Flush Waits/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_write_seconds{instance=\"$server\", mssql_instance=\"$dbinstance\"})",
       "legendFormat": "Log Flush Write Seconds/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_flushed_bytes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Flushed Bytes/sec"
      },
      {
       "expr": "sum(rate(windows_mssql_databases_log_flushes{instance=\"$server\", mssql_instance=\"$dbinstance\"}[$interval]))",
       "legendFormat": "Log Flushes/sec"
      }
     ]
    },
    {
     "title": "Database | Log Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_used_percent.*\", instance=\"$server\", mssql_instance=\"$dbinstance\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Lock Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=\"windows_mssql_locks_lock_wait_seconds\", instance=\"$server\", mssql_instance=\"$dbinstance\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "Lock Timeouts",
     "type": "graph",
     "description": "**Lock Timeouts**\n\nNumber of lock requests per second that timed out, but excluding requests for NOWAIT locks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(windows_mssql_locks_lock_timeouts{instance=\"$server\",mssql_instance=\"$dbinstance\"}[$interval])",
       "legendFormat": "{{ resource }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_logical_disk_size_bytes.*\", instance=\"$server\", volume!~\"Harddisk.+\"} - {__name__=~\"^windows_logical_disk_free_bytes.*\", instance=\"$server\", volume!~\"Harddisk.+\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ volume }}"
      }
     ]
    },
    {
     "title": "Available Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"windows_logical_disk_free_bytes.*\",instance=\"$server\", volume!~\"Harddisk.+\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ volume }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "**Network Traffic**\n\nHere we can see how much network traffic is generated by the Server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(windows_net_bytes_received_total{instance=\"$server\"}[$interval]) or irate(windows_net_bytes_received_total{instance=\"$server\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "expr": "rate(windows_net_bytes_sent_total{instance=\"$server\"}[$interval]) or irate(windows_net_bytes_sent_total{instance=\"$server\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Network Usage Hourly",
     "type": "graph",
     "description": "**Network Usage Hourly**\n\nHere we can see how much network traffic is generated by the Server per hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "increase(windows_net_bytes_received_total{instance=\"$server\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "expr": "increase(windows_net_bytes_sent_total{instance=\"$server\"}[1h])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}