{
 "title": "Server Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "query_result(topk(5,sum(node_network_up * (rate(node_network_transmit_bytes_total[1m]) + rate(node_network_receive_bytes_total[1m]))) by (instance) or sum(rate(windows_net_bytes_sent_total{nic!~\"(IBM|isatap)_.+\"}[1m]) + rate(windows_net_bytes_received_total{nic!~\"(IBM|isatap)_.+\"}[1m])) by (instance)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOP 5 Server CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(5,(100 - (avg by(instance,host) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)) or (100 - (avg by(instance,host) (rate(windows_cpu_time_total{mode=\"idle\"}[$__rate_interval])) * 100))),\"instance\",\"$1\",\"instance\",\"(.+):.+\")",
     "legendFormat": "{{host}}({{instance}})"
    }
   ]
  },
  {
   "title": "Top 5 Server Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(5,((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100) or (100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100))),\"instance\",\"$1\",\"instance\",\"(.+):.+\")",
     "legendFormat": "{{host}}({{instance}})"
    }
   ]
  },
  {
   "title": "Top 5 Server Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(5,label_replace(100 - node_filesystem_avail_bytes{fstype=~\"(xfs|ext4)\",mountpoint!=\"/boot\"} / node_filesystem_size_bytes{fstype=~\"(xfs|ext4)\",mountpoint!=\"/boot\"} * 100,\"volume\",\"$1\",\"mountpoint\",\"(.+)\") or (100 - 100 * ((windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.+\"} / 1024 / 1024) / (windows_logical_disk_size_bytes{volume!~\"HarddiskVolume.+\"} / 1024 / 1024)))),\"instance\",\"$1\",\"instance\",\"(.+):.+\")",
     "legendFormat": "{{host}}({{instance}}) {{volume}}"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(sort_desc(label_replace((node_time_seconds - node_boot_time_seconds) * on (instance) group_right(node_os_info) node_os_info,\"product\",\"$1\",\"name\",\"(.+)\") or ((time() - windows_system_system_up_time) * on (instance) group_right(windows_os_info) windows_os_info)),\"instance\",\"$1\",\"instance\",\"(.+):.+\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Average Temperature",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sort_desc(avg (node_hwmon_temp_celsius) by (location))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "TOP 5 Server Network Sent Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace((sum(node_network_up * rate(node_network_transmit_bytes_total{instance=~\"$instance\",device!~\"br.+\"}[$__rate_interval])) by (instance,host)) or (sum(rate(windows_net_bytes_sent_total{instance=~\"$instance\",nic!~\"(IBM|isatap)_.+\"}[$__rate_interval])) by (instance,host)),\"instance\",\"$1\",\"instance\",\"(.+):.+\")",
     "legendFormat": "{{host}}({{instance}})"
    }
   ]
  },
  {
   "title": "TOP 5 Server Network Received Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace((sum(node_network_up * rate(node_network_receive_bytes_total{instance=~\"$instance\",device!~\"br.+\"}[$__rate_interval])) by (instance,host)) or (sum(rate(windows_net_bytes_received_total{instance=~\"$instance\",nic!~\"(IBM|isatap)_.+\"}[$__rate_interval])) by (instance,host)),\"instance\",\"$1\",\"instance\",\"(.+):.+\")",
     "legendFormat": "{{host}}({{instance}})"
    }
   ]
  },
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance,host)",
     "legendFormat": "http://{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  { "title": "Current Unresolved Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 } }
 ]
}